SuperZooper3/reci

backend/sql/getAccountFollowers.sql
backend/sql/init.sql

https://github.com/SuperZooper3/reci/issues/39

feat: add getAccountFollowers.sql

---

backend/src/controllers/accountController.ts
backend/src/index.ts
backend/src/models/accountModel.ts
backend/src/routes/accountRoutes.ts

Closes https://github.com/SuperZooper3/reci/issues/56
With the refactor from one file into route, controller, and model, as well as the change in convention from users to accounts, the backend account api endpoint stopped working. This fixes that

fix: fixed issues from user to account refactor

---

backend/sql/getAccountRecipes.sql
backend/sql/getAccountReviews.sql

Closes https://github.com/SuperZooper3/reci/issues/37
Also improves some logic to getting the reviews

feat: add getAccountRecipes.sql

---

package.json

Closes https://github.com/SuperZooper3/reci/issues/54

fix: reset db when npm run dev

---

backend/sql/getFolloweeCount.sql
backend/sql/getFollowerCount.sql

Closes
https://github.com/SuperZooper3/reci/issues/64
https://github.com/SuperZooper3/reci/issues/63

Creates SQL files to get follower and followee count

---

backend/sql/getAccountReviewCount.sql

closes https://github.com/SuperZooper3/reci/issues/59

feat: query to get review count

---

backend/sql/saveRecipe.sql

closes https://github.com/SuperZooper3/reci/issues/58

feat: query to save recipe

---

backend/sql/init.sql

Adds cascade deletes to rows referencing account ids

Adds account deletion cascading

---

backend/sql/init.sql
backend/sql/seed.sql

closes https://github.com/SuperZooper3/reci/issues/45

feat: add more seeding data

---

backend/sql/init.sql

Closes https://github.com/SuperZooper3/reci/issues/51
- makes ids increment by making them serial
- defaults date to current timestamp

Makes ids serial

---

backend/sql/getAccountRecipes.sql
backend/sql/seed.sql
backend/src/controllers/recipeController.ts
backend/src/index.ts
backend/src/models/recipeModel.ts
backend/src/routes/recipeRoutes.ts
frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/ui/input.tsx

Closes https://github.com/SuperZooper3/reci/issues/80
This is what the app looks like now!
Note there is still some css and frontend magic to do later. The markdown does not fully render nicely yet. Will make a new issue.

feat: Added recipes endpoint, shadcn input, and markdown support

---

backend/src/models/recipeModel.ts
frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/recipeModal.tsx
frontend/src/components/ui/dialog.tsx
frontend/src/components/ui/label.tsx
frontend/src/components/ui/textarea.tsx

closes https://github.com/SuperZooper3/reci/issues/128
**Recipe modal open:**
**Recipe modal after typing:**
**Recipe added - API success:**
**Recipe appears in DB:**
No confetti affect yet. Still some polishing that can be done for perfect style

feat: added the recipe modal

---

backend/sql/filterRecipes.sql
backend/sql/seed.sql
backend/src/controllers/recipeController.ts
backend/src/models/recipeModel.ts
backend/src/routes/recipeRoutes.ts
backend/src/utils/saveQueryResult.ts

closes https://github.com/SuperZooper3/reci/issues/122
Fixes saveQueryResults.ts to not throw an error if a SQL query returns 0 rows
Creates a getRecipes endpoint. Accepts a query parameter, searchTerm, which filters recipes by title and body, case insensitive.
Initial recipes in DB:
searching returns all recipes with the searchTerm as a substring in title or body, case-insensitive and returning title matches first:

Creates search endpoint

---

backend/sql/getRecipe.sql
backend/sql/getReview.sql
backend/sql/getReviewsByRecipe.sql
backend/src/controllers/reviewController.ts
backend/src/models/reviewModel.ts
backend/src/routes/recipeRoutes.ts
backend/src/routes/reviewRoutes.ts
frontend/src/App.tsx
frontend/src/pages/RecipePage.tsx
frontend/src/pages/SearchPage.tsx
frontend/src/services/recipeService.ts
frontend/src/services/reviewService.ts
shared-types/recipeTypes.ts
shared-types/reviewTypes.ts

- Adds new recipe view page: test by going to http://localhost:5173/recipe/1
- Refactors some backend logic to return username along with reviews/recipes

Creates recipe view page

---

backend/sql/getAccountSavedRecipes.sql
backend/sql/init.sql

Closes https://github.com/SuperZooper3/reci/issues/107

fix: Recipie survives account deletion

---

frontend/src/components/app-sidebar.tsx
frontend/src/components/recipeModal.tsx
frontend/src/services/accountService.ts
frontend/src/services/recipeService.ts

closes https://github.com/SuperZooper3/reci/issues/173

refactor: add recipe through frontend service

---

backend/sql/addReview.sql
backend/sql/addReviewImage.sql
backend/sql/getReviewImages.sql
backend/sql/init.sql
backend/sql/seed.sql
backend/src/controllers/feedController.ts
backend/src/controllers/reviewController.ts
backend/src/models/reviewModel.ts
backend/src/services/feedService.ts
backend/src/services/reviewImageService.ts
backend/src/services/reviewService.ts
frontend/src/components/reviewModal.tsx
shared-types/feedTypes.ts
shared-types/reviewTypes.ts

Also modified the endpoints for feed to return reviews, as well as get review. When you create a review, you can also pass an array of images and alts and it'll add them all.
closes: https://github.com/SuperZooper3/reci/issues/179

feat: Add images to reviews

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/app-sidebar.tsx
frontend/src/components/loginModal.tsx
frontend/src/components/ui/tabs.tsx
frontend/src/pages/HomePage.tsx
frontend/src/pages/SettingsPage.tsx

closes https://github.com/SuperZooper3/reci/issues/134

feat: added login modal

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.css
frontend/src/App.tsx
frontend/src/components/reviewCard.tsx
frontend/src/components/ui/carousel.tsx
frontend/src/pages/HomePage.tsx
frontend/src/pages/RecipePage.tsx

Adds images to reviews.
Closes https://github.com/SuperZooper3/reci/issues/195

Add images to reviews

---

backend/sql/deleteSavedRecipe.sql
backend/src/controllers/recipeController.ts
frontend/src/components/app-sidebar.tsx
frontend/src/pages/RecipePage.tsx
frontend/src/services/recipeService.ts

Adds save button to recipe page.
Toggling it adds and removes from the user's saved recipes.
closes https://github.com/SuperZooper3/reci/issues/241

Adds save button to recipe page

---

backend/src/controllers/recipeController.ts

Fixes missing ratings in cookbook recipes

Add rating to cookbook

---

frontend/src/components/deleteAccountModal.tsx
frontend/src/components/reviewModal.tsx
frontend/src/pages/RecipePage.tsx
frontend/src/pages/SearchPage.tsx
frontend/src/utils/ratingUtils.ts

1. Updates review modal to add images URLs and alts.
2. Makes recipe reviews automatically refresh after adding a review
3. Remove error after deleting account
4. Search page doesn't search by default anymore
5. Adds error message if you try to add duplicate cooks to a recipe

Updates review modal

---

backend/sql/getAccountRecipes.sql
backend/sql/getAccountReviews.sql
frontend/src/components/recipeCard.tsx

Fixes some issues in user page:
uploaded recipes always saying created by unknown user 
reviews not showing the recipe being reviewed
Also a misc bigfix for account links in recipe cards not properly linking to the account page. 
Recipes now properly show created by (prev just said "unknown user"):
Reviews now show the reviewed recipe (Previously just said "this" instead of having a link to it)

Adds info to user page
